### ISSUE TITLE
Proposal voting not working properly

### ISSUE THREAD

**Issue by alex1s1** [particl/particl-market#459]
While voting on proposals I was encountering different errors. 
Although it seems like the vote counted anyway. After changing the vote it also happened that I voted for A and B at the same time. 
Same goes for flagging a listing. Got an error but the listing wasn’t shown anymore (at least for me). 
<img width="1382" alt="5B649DAC-9E30-4C2F-ACF6-D386E8B1BDA5" src="https://user-images.githubusercontent.com/24900581/62532172-1fa98100-b844-11e9-88a5-8dea70b9a3e0.png">
<img width="1382" alt="D96A6316-76D5-437D-97AA-2A70C99A15B1" src="https://user-images.githubusercontent.com/24900581/62532174-1fa98100-b844-11e9-9289-48b95fba2ed7.png">

**Comment by zaSmilingIdiot** [comment]
Please note that this is an older testnet build which was since superseded by a newer testnet build (which would have been in effect already around the time that the issue seems to have been logged).

The testnet builds have since been removed from the https://github.com/particl/particl-desktop releases pages due to the promotion of the features to mainnet. New testnet versions will be released once updated features and resolved issues are ready to be tested again.

**Comment by xludx** [comment]
gui issue
